# ansible/roles/stripe/tasks/show-secret.yml
---
- name: Read Stripe listener logs
  ansible.builtin.command:
    cmd: "docker logs stripe-{{ item.name }}"
  loop: "{{ stripe_instances }}"
  register: stripe_logs
  changed_when: false

- name: Display Stripe logs
  ansible.builtin.debug:
    msg: "{{ item.stdout_lines }}"
  loop: "{{ stripe_logs.results }}"
