- name: Create Forgejo directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "0755"
  loop:
    - "{{ forgejo_dir }}"
    - "{{ forgejo_data_dir }}"

- name: Copy Forgejo env file
  ansible.builtin.template:
    src: forgejo.env.j2
    dest: "{{ forgejo_dir }}/.env"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "0600"

- name: Copy Forgejo docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ forgejo_dir }}/docker-compose.yml"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "0644"

- name: Start Forgejo
  community.docker.docker_compose_v2:
    project_src: "{{ forgejo_dir }}"
    state: present
