---
- name: Configure homelab server
  hosts: homelab
  become: true
  roles:
    - common
    - base
    - role: docker
      when: not (ansible_is_docker_test | default(false))
    - forgejo
    - syncthing
