---
- name: Configure homelab server
  hosts: homelab
  become: true
  roles:
    # - base
    # - node
    # - uv
    # - git
    # - docker
    # - forgejo
    # - syncthing
    # - hermes
    - hermes_skills
    # - searxng
    # - mem0
